# Change these first
owner: Jpsern # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Jpsern.com
    url: https://jpsern.com
    icon: https://jpsern.com/images/favicon-g.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jpsern Server Status
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # Available themes are light, dark, or ocean.
  # theme: dark

# change commit user
# commitMessages:
#   commitAuthorName: Jpsern
#   commitAuthorEmail: xxxxxxxxxxxxxxxxx

workflowSchedule:
#  graphs: "0 0 * * *"
#  responseTime: "0 23 * * *"
#  staticSite: "0 1 * * *"
#  summary: "0 0 * * *"
#  updateTemplate: "0 0 * * *"
#  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
